name-template: v$NEXT_MINOR_VERSION

tag-template: v$NEXT_MINOR_VERSION

categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📦 Dependencies
    label: dependencies

template: |
  ## What's new

  $CHANGES

  __Thanks to:__ $CONTRIBUTORS
